[settings]
class = "CSupport"

[[subpages]]
list = [
    { page = "support", subpage = "" },
    { page = "support", subpage = "Contact Us", route = "contact" },
    { page = "support", subpage = "Separator" },
    { page = "support", subpage = "Hot Keys", route = "keys" },
    { page = "support", subpage = "Icons" },
    { page = "support", subpage = "Documentation" },
    { page = "support", subpage = "Separator" },
    { page = "support", subpage = "Licensing" },
    { page = "support", subpage = "About Us", route = "about" },
]
